:c:func:`PyExceptionClass_Name` will now return ``const char *`` instead of
``char *``.
